name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        run: sudo docker pull bluefincake/devops_rag:latest
      - name: Delete Old docker container
        run: sudo docker rm -f devops_rag-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8080 --name devops_rag-container bluefincake/devops_rag
